### ISSUE TITLE
later versions of `compiler` is missing in gradle plugin portal

### ISSUE THREAD

**Issue by Taskeren** [Him188/kotlin-jvm-blocking-bridge#23]
I've tried `3.1.0-182.1`, `3.1.0-180.1`, and they are error because of missing the compiler.

**Comment by Him188** [comment]
Can you please attach your `build.gradle.kts`?

**Comment by Taskeren** [comment]
I've removed the plugin now, and I reproduced this problem in a random project.

<details>
<summary>build.gradle.kts</summary>

```kts
@file:Suppress("LocalVariableName")

import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    kotlin("jvm") version "1.9.10"
    application
    id("org.jetbrains.kotlin.plugin.serialization") version "1.9.10"

    id("me.him188.kotlin-jvm-blocking-bridge") version "3.1.0-182.1"
}

group = "cn.taskeren.opus"
version = "1.0-SNAPSHOT"

repositories {
    mavenCentral()
}

dependencies {
    val ktor_version = "2.3.4"
    val logback_version = "1.4.11"
    implementation("io.ktor:ktor-server-core:$ktor_version")
    implementation("io.ktor:ktor-server-netty:$ktor_version")
    implementation("io.ktor:ktor-server-content-negotiation:$ktor_version")
    implementation("io.ktor:ktor-serialization-kotlinx-json:$ktor_version")
    implementation("ch.qos.logback:logback-classic:$logback_version")
    implementation("org.jetbrains.kotlinx:kotlinx-datetime:0.4.1")
    testImplementation("io.ktor:ktor-server-test-host:$ktor_version")

    implementation("me.him188:kotlin-jvm-blocking-bridge-runtime:3.1.0-182.1")

    testImplementation(kotlin("test"))
}

tasks.test {
    useJUnitPlatform()
}

tasks.withType<KotlinCompile> {
    kotlinOptions.jvmTarget = "1.8"
}

application {
    mainClass.set("MainKt")
}
```

</details>

<details>
<summary>Output Log</summary>

```
A problem occurred configuring root project 'opus-pastbin'.
> Could not resolve all files for configuration ':classpath'.
   > Could not find me.him188:kotlin-jvm-blocking-bridge-compiler:3.1.0-182.1.
     Searched in the following locations:
       - https://plugins.gradle.org/m2/me/him188/kotlin-jvm-blocking-bridge-compiler/3.1.0-182.1/kotlin-jvm-blocking-bridge-compiler-3.1.0-182.1.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project : > me.him188.kotlin-jvm-blocking-bridge:me.him188.kotlin-jvm-blocking-bridge.gradle.plugin:3.1.0-182.1 > me.him188:kotlin-jvm-blocking-bridge-gradle:3.1.0-182.1

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

</details>

And as I open `https://plugins.gradle.org/m2/me/him188/kotlin-jvm-blocking-bridge-compiler/3.1.0-182.1/kotlin-jvm-blocking-bridge-compiler-3.1.0-182.1.pom` in browser, it redirects to `https://jcenter.bintray.com/me/him188/kotlin-jvm-blocking-bridge-compiler/3.1.0-182.1/kotlin-jvm-blocking-bridge-compiler-3.1.0-182.1.pom`, which gives the text following:

```json
{
  "errors" : [ {
    "status" : 404,
    "message" : "Could not find resource"
  } ]
}
```

**Comment by Him188** [comment]
Thanks for your clarification. 

I've checked on Maven Central <https://repo.maven.apache.org/maven2/me/him188/kotlin-jvm-blocking-bridge-compiler/> that the compiler version `3.1.0-180.1` is indeed missing. 

However, since there is no update in the compiler from `3.0.0` to `3.1.0`. You may continue using the `3.0.0-180.1` compiler version: [3.0.0-180.1/](https://repo.maven.apache.org/maven2/me/him188/kotlin-jvm-blocking-bridge-compiler/3.0.0-180.1/). You just need to change:
- the plugin `id("me.him188.kotlin-jvm-blocking-bridge") version "3.0.0-180.1"`
- the dependency `implementation("me.him188:kotlin-jvm-blocking-bridge-runtime:3.0.0-180.1")`

To eliminate confusion, I will upload the `3.1.0` compiler, hopefully by this weekend.

----

BTW, I noticed you are using Kotlin `1.9.10`, which was not tested for compatibility with KJBB `3.1.0`. You can try this pairing, and feel free to knock me if it is incompatible (does not compile).

**Comment by Taskeren** [comment]
Thanks, I've figure it out by using 3.0.0 before open this issue. lol
